owner: pontusk
repo: upptime

sites:
  - name: RPG Go
    url: https://rpg.illustrius.se
  - name: Recipes
    url: https://recipes.junknet.xyz
  - name: Books
    url: https://calibre.junknet.xyz
  - name: Shadowrun rules wiki
    url: https://sr-wiki.junknet.xyz

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This page contains uptime info for Pontus's sites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
